FROM node:21-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json ./

RUN npm install

FROM node:21-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run  build

EXPOSE 3000

ENV PORT 3000

CMD ["npm", "start"]
