  add/support[m
  adding/fixes[m
  apples-fixing[m
  apples_fix[m
  apples_win_anim[m
  banners-add[m
  banners-fix[m
  banners-fixinng[m
  blackJack[m
  carRace[m
  cars/horse_winBlock[m
  features/add[m
  fixes-adding[m
  fixing[m
  fixxes[m
* [32mgame_layout[m
  game_sidebar[m
  graphic[m
  music[m
  new_footer[m
  new_registr[m
  p2p[m
  payment[m
  payment_next[m
  registr/adaptive[m
  registr/manual[m
  roluette[m
  sidebar-fixing[m
  sidebar_add[m
  slots[m
  sound-btns/fix[m
  swiper-fix[m
  swiperHeightRemoving[m
  test-wagmi[m
  test_fixes[m
  test_payment[m
  testssa[m
  thimbles[m
  vip_page[m
  wager-btns-fix[m
  web2_cloned[m
  web_2[m
  wheel[m
  win-block[m
