export const ABI = [
  {
    inputs: [
      { internalType: "address", name: "_bankroll", type: "address" },
      { internalType: "address", name: "_vrf", type: "address" },
      { internalType: "address", name: "link_eth_feed", type: "address" },
      { internalType: "uint8[24]", name: "maxReveal", type: "uint8[24]" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AlreadyInGame", type: "error" },
  {
    inputs: [{ internalType: "uint256", name: "requestID", type: "uint256" }],
    name: "AwaitingVRF",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint256", name: "have", type: "uint256" },
      { internalType: "uint256", name: "want", type: "uint256" },
    ],
    name: "BlockNumberTooLow",
    type: "error",
  },
  { inputs: [], name: "InvalidNumMines", type: "error" },
  {
    inputs: [
      { internalType: "uint32", name: "numberPicked", type: "uint32" },
      { internalType: "uint256", name: "maxAllowed", type: "uint256" },
    ],
    name: "InvalidNumberToReveal",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint256", name: "required", type: "uint256" },
      { internalType: "uint256", name: "sent", type: "uint256" },
    ],
    name: "InvalidValue",
    type: "error",
  },
  { inputs: [], name: "NoRequestPending", type: "error" },
  { inputs: [], name: "NotApprovedBankroll", type: "error" },
  { inputs: [], name: "NotInGame", type: "error" },
  {
    inputs: [
      { internalType: "address", name: "want", type: "address" },
      { internalType: "address", name: "have", type: "address" },
    ],
    name: "NotOwner",
    type: "error",
  },
  {
    inputs: [
      { internalType: "address", name: "have", type: "address" },
      { internalType: "address", name: "want", type: "address" },
    ],
    name: "OnlyCoordinatorCanFulfill",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint256", name: "suspensionTime", type: "uint256" },
    ],
    name: "PlayerSuspended",
    type: "error",
  },
  { inputs: [], name: "RefundFailed", type: "error" },
  {
    inputs: [{ internalType: "uint8", name: "position", type: "uint8" }],
    name: "TileAlreadyRevealed",
    type: "error",
  },
  { inputs: [], name: "TransferFailed", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "wager", type: "uint256" },
      { internalType: "uint256", name: "maxWager", type: "uint256" },
    ],
    name: "WagerAboveLimit",
    type: "error",
  },
  { inputs: [], name: "ZeroWager", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "playerAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "wager",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "payout",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "multiplier",
        type: "uint256",
      },
    ],
    name: "Mines_End_Event",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "player",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "wager",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
    ],
    name: "Mines_Refund_Event",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "playerAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "wager",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "payout",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool[25]",
        name: "minesTiles",
        type: "bool[25]",
      },
      {
        indexed: false,
        internalType: "bool[25]",
        name: "revealedTiles",
        type: "bool[25]",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "multiplier",
        type: "uint256",
      },
    ],
    name: "Mines_RevealCashout_Event",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "playerAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "wager",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "payout",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool[25]",
        name: "minesTiles",
        type: "bool[25]",
      },
      {
        indexed: false,
        internalType: "bool[25]",
        name: "revealedTiles",
        type: "bool[25]",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "multiplier",
        type: "uint256",
      },
    ],
    name: "Mines_Reveal_Event",
    type: "event",
  },
  {
    inputs: [],
    name: "Bankroll",
    outputs: [
      { internalType: "contract IBankRoll", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ChainLinkVRF",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "IChainLinkVRF",
    outputs: [
      { internalType: "contract IVRFCoordinatorV2", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "LINK_ETH_FEED",
    outputs: [
      {
        internalType: "contract AggregatorV3Interface",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "Mines_End",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "Mines_GetMaxReveal",
    outputs: [
      { internalType: "uint256[24]", name: "maxReveal", type: "uint256[24]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "numMines", type: "uint256" },
      { internalType: "uint256", name: "numRevealed", type: "uint256" },
    ],
    name: "Mines_GetMultipliers",
    outputs: [{ internalType: "uint256", name: "multiplier", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "player", type: "address" }],
    name: "Mines_GetState",
    outputs: [
      {
        components: [
          { internalType: "address", name: "tokenAddress", type: "address" },
          { internalType: "uint256", name: "wager", type: "uint256" },
          { internalType: "uint256", name: "requestID", type: "uint256" },
          { internalType: "uint64", name: "blockNumber", type: "uint64" },
          { internalType: "uint64", name: "currentMultiplier", type: "uint64" },
          { internalType: "uint8", name: "numMines", type: "uint8" },
          { internalType: "bool[25]", name: "revealedTiles", type: "bool[25]" },
          { internalType: "bool[25]", name: "tilesPicked", type: "bool[25]" },
          { internalType: "bool", name: "isCashout", type: "bool" },
        ],
        internalType: "struct Mines.MinesGame",
        name: "minesState",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "Mines_Refund",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bool[25]", name: "tiles", type: "bool[25]" },
      { internalType: "bool", name: "isCashout", type: "bool" },
    ],
    name: "Mines_Reveal",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "numMines", type: "uint256" }],
    name: "Mines_SetMultipliers",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "wager", type: "uint256" },
      { internalType: "address", name: "tokenAddress", type: "address" },
      { internalType: "uint8", name: "numMines", type: "uint8" },
      { internalType: "bool[25]", name: "tiles", type: "bool[25]" },
      { internalType: "bool", name: "isCashout", type: "bool" },
    ],
    name: "Mines_Start",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "VRFFees",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "gasAmount", type: "uint256" }],
    name: "getVRFFee",
    outputs: [{ internalType: "uint256", name: "fee", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "requestId", type: "uint256" },
      { internalType: "uint256[]", name: "randomWords", type: "uint256[]" },
    ],
    name: "rawFulfillRandomWords",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "to", type: "address" }],
    name: "transferFees",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
